### ISSUE TITLE
Crash on opening save game - 21.10.19

### ISSUE THREAD

**Issue by Riaktion** [TerryCavanagh/diceydungeons.com#1509] opened 2019-10-21 18:45 UTC
--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v1.5 / 0.12.0 (mod API)
sess. ID:	dicey_dungeons_2019-10-21_19'39'15
started:	2019-10-21 19:39:15
--------------------------------------
crashed:	2019-10-21 19:39:20
duration:	00:00:05
error:		ERROR in callscenemethod(DoYouWantToContinue,update) static : Null Object Reference, stack = 
Called from elements.Floor.updatenodedata (elements/Floor.hx line 1437)
Called from utils.ContinueSave.applysaveddata (utils/ContinueSave.hx line 375)
Called from states.Episodestate.continuegame (states/Episodestate.hx line 329)
Called from states.DoYouWantToContinue.update (states/DoYouWantToContinue.hx line 44)
Called from FadeControl.update (FadeControl.hx line 78)
Called from Screen.endrender (Screen.hx line 274)
Called from states.DoYouWantToContinue.update (states/DoYouWantToContinue.hx line 67)
Called from Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 268)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 182)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

Thanks!

**Comment by TerryCavanagh** [comment] 2019-11-12 18:45
Thanks for this! I believe this is a duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/1544. Should be fixed soon!

**Closed by TerryCavanagh** 2019-11-12 18:45 UTC
Labels: reported in v1.6
