### ISSUE TITLE
Freezing Cauldron vs. Gargoyle

### ISSUE THREAD

**Issue by davecom3** [TerryCavanagh/diceydungeons.com#1461] opened 2019-09-15 22:49 UTC
Freezing Cauldron acts as if you have never rolled a die before in the turn, meaning that if you face the Gargoyle and use the Freezing Cauldron to lock its dice, not only does it lock the first die or two, but also each die returned when you use the Freezing Cauldron to make the Gargoyle roll a 1.

**Comment by findersjeepers** [comment] 2019-09-16 00:28
Duplicate of #1458

**Comment by TerryCavanagh** [comment] 2020-09-25 04:26
Fixed!

**Closed by TerryCavanagh** 2020-09-25 04:26 UTC
Labels: reported in v1.4
