### ISSUE TITLE
Crash with Thief vs. Copycat

### ISSUE THREAD

**Issue by Moocowsgomoo** [TerryCavanagh/diceydungeons.com#1213] opened 2019-08-17 20:43 UTC
This was during the Thief's "Elimination Round", on floor 3. My equipment was: Dagger, Bandage, Poison Needle, Leather Armor, Lockpick, Pickpocket+. I unequipped everything except Dagger and Lockpick before the fight and it crashed right after showing the "Innate" tooltip in combat. I tried re-adding equipment one at a time, but it still crashes consistently even with all slots filled in.
```
--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v1.0.2 / 0.11.0 (mod API)
sess. ID:	dicey_dungeons_2019-08-17_13'57'40
started:	2019-08-17 13:57:40
--------------------------------------
crashed:	2019-08-17 14:09:49
duration:	00:12:09
error:		ERROR in callscenemethod(Combat,update) static : Null Object Reference, stack = 
Called from states.Combat.update (states/Combat.hx line 246)
Called from Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 268)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 182)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)
```

**Comment by TerryCavanagh** [comment] 2019-08-28 17:49
I've made some fixes to Copycat for v1.3, and I believe this one is fixed, but I can't reproduce this exact crash, so I'm not 100% certain. Going to close for now, please let me know if you (or anyone else reading!) encounters this one again!

**Comment by Turok2009** [comment] 2022-01-08 20:51
I actually just found this site and made an account to say that I am having this very issue. Every time I finish my first turn and it goes to copy cat the game will crash. I’m playing the same elimination chapter too. I had just assumed it was an issue with my weird equipment but I tried no equipment too like the first report mentioned and no luck there either. I’m playing on Xbox one. Just hoping there’s an answer lol.

**Comment by TerryCavanagh** [comment] 2022-01-10 11:15
Hi @Turok2009! I believe this is fixed in the latest update. Are you sure you're fully updated on Xbox one?

**Comment by Volatile-Agent** [comment] 2022-04-16 16:17
Version 1.0.0.2 on Xbox One: Thief (Level 3) vs. Copycat in Elimination Round, floor 3, with equipment Dagger+, Snake Eye Charm,  Pea Shooter, Lockpick, Healing Crystal, and Crowbar. Freezes at start of Copycat’s first turn and eventually returns to home screen. Removing either Lockpick or Crowbar seems to fix it.

**Comment by TerryCavanagh** [comment] 2022-04-19 13:58
Thanks @Volatile-Agent - I'll reopen and investigate this further!

**Comment by TerryCavanagh** [comment] 2022-07-22 17:39
This one is finally fixed, phew

**Closed by TerryCavanagh** 2022-07-22 17:39 UTC
Labels: High Priority, reported in v1.12
