### ISSUE TITLE
Crash to black screen fighting Guardian

### ISSUE THREAD

**Issue by OtherworldBob** [TerryCavanagh/diceydungeons.com#268] opened 2018-06-11 18:09 UTC
Was fighting Guardian, as Witch, a couple of rounds in. Following the Guardian making a move, game crashed to black screen. HTML5, using Firefox. The following was logged to the Console:
uncaught exception: Error: Trying to create equipment "Lightning bolt_upgraded_upgraded" from template, but cannot find a matching template in equipment.csv. 

Called from module __handleError@https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js:91569:40
Called from module __broadcastEvent@https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js:91402:7
Called from module render@https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js:91355:3
Called from module f@https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js:121182:233
Called from module tmp@https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js:90884:4
Called from module dispatch@https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js:37155:4
Called from module handleApplicationEvent@https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js:649:5
Called from module f@https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js:121182:233
Called from module  diceydungeons.js:91570:6

**Comment by TerryCavanagh** [comment] 2018-06-23 17:49
Pretty sure this is fixed, but I can't reproduce it so not 100% sure! (I think this was being caused by problems with the game restoring upgraded equipment that had been weakened, and I'm pretty sure that issue's been fixed now.)

Thanks! Closing.

**Closed by TerryCavanagh** 2018-06-23 17:49 UTC
Labels: reported in v0.8
