### ISSUE TITLE
Shock + weakens on Knight don't add up

### ISSUE THREAD

**Issue by BarbzYHOOL** [TerryCavanagh/diceydungeons.com#313] opened 2018-06-19 21:39 UTC
Shock + weakens on Knight don't add up

it's always weakens

**Comment by onetruepurple** [comment] 2019-05-30 21:47
Duplicate of #367

**Comment by TerryCavanagh** [comment] 2019-05-30 22:01
Yep! Closing, thanks!

**Closed by TerryCavanagh** 2019-05-30 22:01 UTC
Labels: reported in v0.8
