### ISSUE TITLE
Detailed bug reporting on steam

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1355] opened 2019-08-30 15:39 UTC
https://steamcommunity.com/app/861540/discussions/0/1638669204739019025/

**Comment by ncrecc** [comment] 2019-08-31 14:08
_"Definitely bugs"_
1. Dupe of #1115
2. Copycat copies before the first turn, so this is intended
3. Dupe of #1247, though refers to backing out of "delete card" rather than of "upgrade card"
4. Dupe of TerryCavanagh/diceydungeonsbeta/issues/584
5. Dupe of TerryCavanagh/diceydungeonsbeta/issues/174
6. Dupe of TerryCavanagh/diceydungeonsbeta/issues/204
7. This is new, though a logical extension of #210 and #459 (which are fixed)
8. Dupe of TerryCavanagh/diceydungeonsbeta/issues/678
9. Dupe of TerryCavanagh/diceydungeonsbeta/issues/153
10. Dupe of TerryCavanagh/diceydungeonsbeta/issues/704
11. Dupe of TerryCavanagh/diceydungeonsbeta/issues/716
12. Dav999 posted this in #bug-reports, otherwise new
13. Dupe of TerryCavanagh/diceydungeonsbeta/issues/148, also filed under #1343 
_"Unfortunate, unclear or incomplete descriptions"_
1. Might be clearer if thorns and candle didn't pierce? That might be too radical, so maybe just change the heart icon to a sword icon (since most items using the heart refer to piercing damage - backfire doesn't pierce, though, does it? hm)
2. Maybe do something special to make Cardboard Sword lose the "decrease by" line once it's at minimum damage?
_"Unsure if these are even bugs"_
1. Yeah, probably
2. Dupe of TerryCavanagh/diceydungeonsbeta/issues/320
3. Current behavior seems alright to me. I'd figure it makes more sense when presented as, say, reduce by? countering burn all by protecting one dice from being burnt.

**Comment by ncrecc** [comment] 2019-08-31 14:09
After typing all that I'm thinking we should just archive ddbeta now before it gets any more out of hand, and maybe open a new repository if we have to test any DLC or content updates.

**Closed** 2020-09-25 03:06 UTC
Labels: reported in v1.3
