### ISSUE TITLE
Hijinx snap causing dice to unlock

### ISSUE THREAD

**Issue by McKrathus** [TerryCavanagh/diceydungeons.com#1430] opened 2019-09-09 08:02 UTC
Jester VS Paper Knight
Parallel Universe
Witch Extra Card Active
Snap on 2 Hijinx (1 was upgraded)
Unlocked my two locked dice

**Comment by TerryCavanagh** [comment] 2020-06-06 08:26
Can't reproduce this in v1.8, so I think it's fixed! Closing.

**Closed by TerryCavanagh** 2020-06-06 08:26 UTC
Labels: reported in v1.4
