### ISSUE TITLE
Can't cancel spell cast

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#246] opened 2018-06-08 23:13 UTC
Once you've dragged a die into the slot to cast a spell, you can't end your turn without picking a slot.

**Comment by BarbzYHOOL** [comment] 2018-06-12 20:12
Yes, this is one of the bigger bugs

**Comment by TerryCavanagh** [comment] 2019-05-29 23:03
duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/453, closing!

**Closed by TerryCavanagh** 2019-05-29 23:03 UTC
Labels: reported in v0.8
