### ISSUE TITLE
Yeti don't like "Poison?"

### ISSUE THREAD

**Issue by Linkyop** [TerryCavanagh/diceydungeons.com#1636] opened 2020-02-09 12:57 UTC
Game crashed, when his turn started. 1.7.2.

Video: https://streamable.com/n4lqs
Log: [_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/4176884/_error.txt)

**Comment by ncrecc** [comment] 2020-02-10 21:58
Duplicate of #1567 
(Which itself is technically a duplicate of #1356 since this bug relates to AI and multislot equipment in general)

**Comment by TerryCavanagh** [comment] 2020-09-25 05:08
Fixed!

**Closed by TerryCavanagh** 2020-09-25 05:08 UTC
Labels: reported in v1.7
