### ISSUE TITLE
Enough poison? can softlock some enemies (NOT the multislot crash)

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1427] opened 2019-09-09 01:12 UTC
They'll pour some of their dice into the poison?ed card so fast that the total of the dice put in the card exceeds the poison? amount, then sit there confused and never do anything.

**Comment by TerryCavanagh** [comment] 2020-10-21 05:27
Hmm, I spent a little while trying to reproduce this one without any luck. Do you remember any details that might help figure it out? How much poison does it take to cause this problem? Who were you fighting?

(As a rare and difficult to reproduce bug, I'm going to de-prioritise it for v1.10 unless I can figure out a consistent way to reproduce it)

**Comment by TerryCavanagh** [comment] 2020-10-21 05:28
Oh, this one's from v1.4 - that's a while back! There have been some AI changes since then - I wonder if this is actually fixed now?

**Comment by TerryCavanagh** [comment] 2022-07-25 16:20
Well, have had no reports of this happening in almost two years, and I suspected it was fixed already when I looked into it then - so I'm thinking it's probably fixed, or so rare that it's safe to close. If it happens again I'll make a new issue!

**Closed by TerryCavanagh** 2022-07-25 16:20 UTC
Labels: reported in v1.4
