### ISSUE TITLE
FREEn slots (e.g. broadsword) count toward total when unlocking passworded card

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2946] opened 2022-07-21 09:51 UTC
![image](https://user-images.githubusercontent.com/11216597/180184447-847a7fbf-5fc3-4b08-ba4b-774e51400476.png)
not sure what is going on here. the player had another card that was passworded to must equal 9 (worm bite), and they placed the matching dice there and everything worked, but here the must equal 10 password just refused and did nothing when they put the dice in. then, on a later turn the player got another must equal 10 password and put the correct dice in and it *did* work.

this was a discord stream, not archived or anything, sadly. possibly an issue with unlocking multiple passworded cards in 1 turn? or just inventor reunion weirdness

**Comment by S2dd7** [comment] 2022-07-21 12:03
hi i was the person who streamed this, and i want to add that when i placed two dice that sum up to 7, the card successfully unpassworded for some reason

**Comment by TerryCavanagh** [comment] 2022-07-21 14:41
Interesting - I wonder if this is something specific to cards getting replaced in the Inventor episode? I'll see if I can reproduce it.

**Comment by JuniorUdale** [comment] 2022-07-22 19:32
Olexa encountered this bug in his latest video - https://youtu.be/Vc8CThQOZgc?t=630 10:30

He has Lojinx, Whetstone, Enchanted Shield, Dynamite Stick+, and 4 Password. Dynamite Stick gets Passworded, requiring a 5, but putting a 4 and a 1 into it didn't work.

**Comment by Matz-42** [comment] 2022-07-22 20:09
Both Frog Sword and Dynamite Stick have a "Free dice" slot, might be related to this.

**Comment by JuniorUdale** [comment] 2022-07-23 00:08
That looks like the bug - free slots are being added to the total. Here, Broadsword (free2) unlocked with a 7, despite the total needing 9.
![image](https://user-images.githubusercontent.com/32357485/180582199-bb874491-8f5e-4fff-b503-f0b7932c4e55.png)

**Comment by TerryCavanagh** [comment] 2022-07-25 11:32
Thanks all! Yep, I can confirm that the free slots were causing the problem (shame that this happened on camera to Olexa 😔 ). Should be fixed in the next update!

**Closed by TerryCavanagh** 2022-07-25 11:32 UTC
Labels: reunion, reported in v2.0
