### ISSUE TITLE
Being able to give weakened equipment in the editor

### ISSUE THREAD

**Issue by timeracers** [TerryCavanagh/diceydungeons.com#669] opened 2018-12-06 01:40 UTC
This also doubles as a way to look up weakened equipment.

**Comment by TerryCavanagh** [comment] 2018-12-06 11:49
Thanks! Duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/496, so closing

**Closed by TerryCavanagh** 2018-12-06 11:49 UTC
Labels: reported in v0.14
