### ISSUE TITLE
Jackpot cheat

### ISSUE THREAD

**Issue by OnlyAnAlligator** [TerryCavanagh/diceydungeons.com#1523] opened 2019-10-27 09:19 UTC
Encountered a slightly difficult to trigger bug regarding the Robot's jackpot. I played my last die before hitting a jackpot on the spud cannon, causing it to trigger. However, I then immediately rolled a new die before the attack landed, getting a jackpot before the attack actually landed on the enemy. When the sped cannon attack landed, it did 4 damage to the enemy rather than 2, as if I had triggered the attack AFTER getting the jackpot. It's a difficult bug to cause, requiring a fair amount of luck and fast reflexes, so I haven't gotten a chance to test other similar pieces of equipment, so I don't know if the problem is isolated to the spud cannon, or affects all equipment with variable outcomes based on whether or not you have triggered a jackpot. I am running the latest version up on Steam.

**Comment by findersjeepers** [comment] 2019-10-28 03:18
Duplicate of #1364

**Comment by TerryCavanagh** [comment] 2020-09-25 04:54
Yep, closing as duplicate (but planning to fix for v1.10!)

**Closed by TerryCavanagh** 2020-09-25 04:54 UTC
Labels: reported in v1.6
