### ISSUE TITLE
Equipment can not be weakened and shocked at the same time

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#433] opened 2018-08-06 01:23 UTC
Using 0.11 right now, but maybe this has existed for all versions and I haven't noticed it. Weaken overrides shock, it seems. But is this a bug or another clever elemental-rock-paper-scissors mechanic?

**Comment by onetruepurple** [comment] 2019-05-30 21:47
Duplicate of #367

**Comment by TerryCavanagh** [comment] 2019-05-30 22:02
Yep! Closing.

**Closed by TerryCavanagh** 2019-05-30 22:02 UTC
Labels: reported in v0.11
