### ISSUE TITLE
Player claims to have seen a trade booth in Inventor Bonus Round offering Mechanical Leg

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1580] opened 2019-12-08 22:51 UTC
![image](https://user-images.githubusercontent.com/11216597/70397649-0ecf6e80-19e2-11ea-87ba-88702eb28c52.png)
![image](https://user-images.githubusercontent.com/11216597/70397712-94ebb500-19e2-11ea-816c-7197bf0da40e.png)
![image](https://user-images.githubusercontent.com/11216597/70397761-f875e280-19e2-11ea-9400-4e090ce7e456.png)

Two things wrong with this:
1. inventor never gets trade booths
2. inventor never finds mech leg anywhere

yet I doubt this would be some sort of lie/extreme mixup (unless some people like trolling game devs with false bug reports??). This would mean that at least on some copies of the game, the generators can get seriously mix-matched

Thief can get mech leg in a trade in br, but it's very unlikely this person somehow confused Inventor with Thief

**Comment by TerryCavanagh** [comment] 2020-09-25 05:13
I think this person probably just got something mixed up. There also doesn't seem to have been any reproductions of this since January, which indicates that it was either a mistake or an extreme once off fluke. Closing!

**Closed by TerryCavanagh** 2020-09-25 05:13 UTC
Labels: reported in v1.6
