### ISSUE TITLE
Bonus round - burning 6s plus alternate status effects do not combine/stack

### ISSUE THREAD

**Issue by logical2u** [TerryCavanagh/diceydungeons.com#1482] opened 2019-10-03 13:26 UTC
Apologies for not having a screenshot or precise version info here. I reported this informally to a friend on 2019-09-24 using the (latest at the time) version on Steam, 64-bit, Windows 10.

During a bonus round, I got the modifier "status effects are different" (that is, switching status effects to their parallel universe version) and, subsequently, the modifier "all rolled 6s catch on fire".

However, the rolled 6s counted as Burning, not Burning?, meaning I took damage when attempting to use them and it does not disable equipment. This means you can suffer from both Burning? and Burning simultaneously in certain cases.

**Comment by TerryCavanagh** [comment] 2020-09-25 04:33
Yep, planning to fix this! Duplicate of an earlier issue, though, so this one should be closed.

**Closed by TerryCavanagh** 2020-09-25 04:33 UTC
Labels: reported in v1.4
