### ISSUE TITLE
I when i level up i select to upgrade something and then change my mind i get nothing

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#51] opened 2018-03-31 11:52 UTC
I assume it would be better to bring you back to the previous level up screen rather than quitting out and leaving you with nothing?

**Comment by TerryCavanagh** [comment] 2019-05-29 22:52
duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/387, closing!

**Closed by TerryCavanagh** 2019-05-29 22:52 UTC
