### ISSUE TITLE
Text spoken by the player character at the ending does not have the name header

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2129] opened 2020-10-12 14:04 UTC
I just played a Backstage episode with the Warrior, and when completing it, the text spoken by the player character does not have the name header (in this case, "Warrior"). The text box doesn't appear above the Warrior either, appearing instead over Jester.

The screenshot is in English, but the game was started with Catalan language selected (just in case that has any relevance to the issue). It happens with the following strings:

- Wait,   confetti?
- What's happening?
- Why are   those lights flashing?
- When   we're gone... So... we're free to go? All of us?

Tested on v1.9.1 (Translator Mode).

See attached screenshot:

![missing_header](https://user-images.githubusercontent.com/285008/95755017-24699080-0ca4-11eb-9f52-7190c005ea75.png)

**Comment by Ereza** [comment] 2020-10-12 14:05
This appears to work correctly when viewing the ending through Translator Mode.

**Comment by JuniorUdale** [comment] 2020-10-12 14:44
I think this is a duplicate of #1796 - this bug happens if the final blow is delivered by someone that isn't the player (hence why it works fine in Translator mode)

**Comment by TerryCavanagh** [comment] 2020-10-13 08:03
Ah, yep, this is a duplicate! I really need to get this one fixed before v1.10...

**Closed by TerryCavanagh** 2020-10-13 08:03 UTC
