### ISSUE TITLE
Launch Error: "Could not load module lime@lime_application_create__prime"

### ISSUE THREAD

**Issue by gamerdonkey** [TerryCavanagh/diceydungeons.com#863] opened 2019-02-02 22:57 UTC
I'm seeing crashes on launch with the following error output:

```Called from lime._internal.backend.native.NativeCFFI::boot lime/_internal/backend/native/NativeCFFI.hx line 214
Called from lime._internal.backend.native.NativeCFFI::boot lime/_internal/backend/native/NativeCFFI.hx line 214
Called from cpp.Prime::_loadPrime /usr/share/haxe/std/cpp/Prime.hx line 36
Error : Could not load module lime@lime_application_create__prime
```

OS is 64-bit Linux Mint 18.3 Sylvia (which is based on Ubuntu 16.04 LTS).

I installed the "latest" Lime (7.2.1) through Haxe, but this only changed the error to a segfault on launch.

`./launch.sh: line 2: 17936 Segmentation fault      ./diceydungeons`

**Comment by ThatGuyBob** [comment] 2019-02-28 20:00
Same problem here.  Found in 0.15.1 and 0.16.
```
crashdumper$ ./cpu.sh ; ./gpu.sh ; ./memory.sh ; ./os.sh 
Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
 Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
 NVIDIA Corporation GK107GLM [Quadro K1000M] (rev a1)
       32484236 kB
No LSB modules are available.
    Ubuntu 17.10
x86_64
```

**Comment by jepler** [comment] 2019-03-03 02:29
Affecting me in 0.16.1.  debian stretch x86_64.  Both "linux32" and "linux64" versions are giving similar or the same messages.

The underlying problem seems to be that `lime.ndll` is built to require a newer system library than Debian Stretch and Ubuntu 17.10 have:
```
$ LD_DEBUG=all ./diceydungeons
# Many lines of irrelevant stuff
     28894:	/lib/i386-linux-gnu/libgcc_s.so.1: error: version lookup error: version `GCC_7.0.0' not found (required by ./lime.ndll) (fatal)
# More lines of irrelevant stuff
```

**Comment by babbageclunk** [comment] 2019-03-06 02:46
I get the same error on Ubuntu 16.04, although in my case it's looking for the glibc version rather than gcc.

```
     13127:     checking for version `GLIBC_2.2.5' in file /lib/x86_64-linux-gnu/librt.so.1 [0] required by file ./lime.ndll [0]
     13127:     checking for version `GLIBC_2.2.5' in file /lib/x86_64-linux-gnu/libdl.so.2 [0] required by file ./lime.ndll [0]
     13127:     checking for version `GCC_3.4' in file /lib/x86_64-linux-gnu/libgcc_s.so.1 [0] required by file ./lime.ndll [0]
     13127:     checking for version `GCC_3.0' in file /lib/x86_64-linux-gnu/libgcc_s.so.1 [0] required by file ./lime.ndll [0]
     13127:     checking for version `GLIBC_2.27' in file /lib/x86_64-linux-gnu/libm.so.6 [0] required by file ./lime.ndll [0]
     13127:     /lib/x86_64-linux-gnu/libm.so.6: error: version lookup error: version `GLIBC_2.27' not found (required by ./lime.ndll) (fatal)
```

**Comment by jepler** [comment] 2019-03-06 23:24
fwiw Dicey Dungeons seems to run fine in PlayOnLinux with wine 3.20 on Debian Stretch.  It'll do for now.

**Comment by TerryCavanagh** [comment] 2019-05-11 07:27
Hey! We've been looking into this, and think it might be due to the compiler setup on linux. It should hopefully be fixed for v0.17!

**Comment by jepler** [comment] 2019-05-22 17:03
Unfortunately, the same problem or similar is affecting me on debian stretch, using a fresh download from itch.io today that says it's 0.17.1.

**Comment by TerryCavanagh** [comment] 2019-05-24 20:43
Yep, sorry - I'm going to implement my attempted fix for this in v0.17.2!

**Comment by TerryCavanagh** [comment] 2019-05-29 23:51
Hey all -

To anyone following this thread, I just uploaded a new version to itch, v0.17.2. We used a new compiler set up and I think it should solve this issue. Can anyone confirm? Thanks!

**Comment by buckysrevenge** [comment] 2019-05-31 17:04
I can confirm that I am no longer getting the error message and am able to launch the game successfully, SteamOS beta

**Comment by jepler** [comment] 2019-05-31 22:38
Also fixed on Debian Stretch.  Wahoo, just had a fun (and victorious) playthrough with warrior / parallel universe.

**Comment by TerryCavanagh** [comment] 2019-06-01 15:54
Yay, that's great! Closing this one!

**Closed by TerryCavanagh** 2019-06-01 15:54 UTC
Labels: reported in v0.15.1
