### ISSUE TITLE
Game silently freezes if you call giveequipment in a Before Start Turn or End Turn script

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1572] opened 2019-11-19 00:48 UTC
I'm guessing what it's trying to do in this case is animate the equipment being replaced, and then it runs into something unexpected because the cards are unavailable to be animated? (Note: giveequipment works fine in After Combat and is used with Transformer, also self.replaceskillcard works perfectly fine with Before Start Turn and is used for Uptick)

**Comment by TerryCavanagh** [comment] 2020-01-23 10:30
I'm fairly certain this one is fixed in v1.7 due to changes in how I handle animations, but I'll check before closing it!

**Comment by ncrecc** [comment] 2020-02-02 08:24
This works when it's giving you a new equipment without replacing anything, but when it's meant to replace a card (e.g. giveequipment(\~Broadsword\~|false|false|e)), this error is endlessly outputted to the console:
```
DiceyScript.hx:61: Error executing action "giveequipment("Broadsword",false,false,e);"
Script.hx:606: Unknown Error: Outputting as much detail as we can
Script.hx:607: error: Null Object Reference
Script.hx:608: fields: []
Script.hx:610: interp: { e => EIdent(giveequipment), id => 143, pmax => 12, pmin => 0 }
Script.hx:611: Cannot provide more details yet.
Equipment.hx:444: Warning: Cannot resize to sizes other than 2 right now.
Fighter.hx:1110: Equipment exists in equipment slots but not in equipment array??
```

**Comment by TerryCavanagh** [comment] 2020-06-12 07:53
This one is fixed! Using giveequipment in either Before Start Turn or End Turn equipment scripts now works as intended.

This was an interesting bug to fix! Ended up fixing a bunch of adjacent scripting and inventory issues in the process, and improved error handling and reporting.

**Closed by TerryCavanagh** 2020-06-12 07:53 UTC
Labels: Random Bug Lottery, modding issue, reported in v1.6
