### ISSUE TITLE
Weakening cards removes their "once per turn" restriction

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#484] opened 2018-09-03 15:34 UTC
e.g. with Bully's rocks:

https://gfycat.com/DependentUnlinedAidi

**Comment by krsiehl** [comment] 2018-09-03 18:50
There is a similar effect when you weaken Paper Knight's attack, where the weakening-over-time effect doesn't carry over to the next turn

**Comment by onetruepurple** [comment] 2018-09-04 11:56
(duplicate of #424 )

**Closed** 2019-05-29 23:09 UTC
Labels: reported in v0.12
