### ISSUE TITLE
Dice highlight (when clicking a die) is barely noticeable

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#243] opened 2018-06-05 01:48 UTC
When you click a die, before clicking on a piece of equipment to put it in, the die becomes very slightly brighter; however, the effect is so subtle that it's almost unnoticeable. The highlighted die should be much, much more obvious.

**Comment by TerryCavanagh** [comment] 2019-05-29 22:28
Dice highlight has been removed completely since Marlowe's graphics got added! This still needs to be done, but closing since it's a duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/208.

**Closed by TerryCavanagh** 2019-05-29 22:28 UTC
Labels: reported in v0.7.1
