### ISSUE TITLE
Damaging yourself causes thorns to further damage you, including picking up burned dice

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1797] opened 2020-07-13 18:46 UTC
Damage from a burnt dice shouldn't be considered as coming *from* any particular entity.
This also affects self-damage taken from Boomerang and Double Edge, although in that case taking thorns damage is more logical since you're literally attacking yourself.

**Comment by TerryCavanagh** [comment] 2022-07-26 17:42
This is a duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/1455! I suspect this is fixed already, I just need to double check it.

**Closed by TerryCavanagh** 2022-07-26 17:42 UTC
Labels: reported in v1.8, C - Rare/requires weird actions, 2 - Has Negative Effects, Priority
