### ISSUE TITLE
If hard-mode enemy's equipment weakened, subsequent steal will return non-upgraded equipment

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#365] opened 2018-07-04 02:51 UTC
Fighting against a Sorceress in hard mode, I used her own Hex to weaken two pieces of her equipment, which happened to include her Cauldron+. The next turn, the thief's steal turned up a Cauldron, not a Cauldron+.

**Comment by TerryCavanagh** [comment] 2019-05-29 22:53
Duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/391, thanks!

**Closed by TerryCavanagh** 2019-05-29 22:53 UTC
Labels: reported in v0.9.1
