### ISSUE TITLE
Ghost Dice

### ISSUE THREAD

**Issue by retroporter42** [TerryCavanagh/diceydungeons.com#1983] opened 2020-09-24 17:41 UTC
Playing in 1.9, as the Jester against the Wisp. If the Wisp inflicts vanish and you use your limit break to snap a pair of cards. When the animation shows two dice of the same value activating the cards, due to vanish one of the dice is removed as it is played. This results in a 'ghost dice' floating on the screen that can't be interacted with.
https://gyazo.com/d2c6fcd81c148a84a279e2bba57ee828

**Comment by JuniorUdale** [comment] 2020-09-24 22:15
Duplicate of #1969

**Comment by TerryCavanagh** [comment] 2022-08-09 11:43
Fixed for v2.1!

**Closed by TerryCavanagh** 2022-08-09 11:43 UTC
Labels: reported in v1.9
