### ISSUE TITLE
wall of flame is not once per battle upon being weakened as the description says

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#519] opened 2018-09-29 11:43 UTC
https://youtu.be/FdcNtlea-90?t=20m19s

**Comment by onetruepurple** [comment] 2018-09-29 12:46
Duplicate of #424

**Comment by TerryCavanagh** [comment] 2019-02-24 22:41
I've removed Wall of Flame, and I'm trying a different design for Dragon now. Thanks!

**Closed by TerryCavanagh** 2019-02-24 22:41 UTC
Labels: reported in v0.13
