### ISSUE TITLE
Make level up rewards swap in "The Robot" rule more flexible

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#1950] opened 2020-09-19 06:18 UTC
Right now, the only way to modify the changed level up rewards in therobot.hx is to erase them again in the appended file and overwrite them. Ideally these should be moved to a list which modders can easily append to for better compatibility.

**Comment by TerryCavanagh** [comment] 2020-09-25 08:09
Yep, will need to fix this at some point. (Duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/1935, so closing this one.)

**Closed by TerryCavanagh** 2020-09-25 08:09 UTC
Labels: reported in v1.9
