### ISSUE TITLE
Minor "Quality of Life" issues

### ISSUE THREAD

**Issue by woctezuma** [TerryCavanagh/diceydungeons.com#490] opened 2018-09-03 15:39 UTC
As the Witch:

- if there is no dice left because they were all thrown, one still has to end the turn manually ; it could be done automatically.

![no dice](https://i.imgur.com/SPIxhr7.jpg)
- while in a fight, there is no way to check what one spell does if we don't remember, so we have to actually blind-buy the spell in this case ; there could be some information displayed when hovering over the spells.

![no hovering](https://i.imgur.com/ZS9DmKF.jpg)

**Comment by YinYin-Falcon** [comment] 2018-09-03 16:02
Keep in mind that you may wanna flee or use the limit. Thus the turn needs to end manually.

**Comment by Wowfunhappy** [comment] 2018-09-04 04:40
Given that Witch always a "Throw Dice" option, does it make sense for her to even have an "End Turn" button?

**Comment by TerryCavanagh** [comment] 2019-05-29 23:08
On the end turn thing: there are too many cases in game where the player is better off having full control over the decision, so I don't think I'm going to add an auto-end turn feature. I think you either want it to always be on or always be off, and since it can't always be on, I'm going to leave it as is.

The second issue is a duplicate of another open issue. Closing this one!

**Closed by TerryCavanagh** 2019-05-29 23:08 UTC
Labels: reported in v0.12
